config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "categories#index"
  
  resources :categories,only: [:index,:show]
  resources :questions,only: [:new,:create,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories=Category.all
  end

  def show
    @category=Category.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question=Question.new
  end

  def create
    @question=Question.new(question_params)
    
    if @question.save
      flash[:success]='登録しました'
      redirect_to root_path
    else
      flash.now[:danger]='登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @question=Question.find(params[:id])
  end
  
  def update
    @question=Question.find(params[:id])
    
    if @question.update(question_params)
      flash[:success]='編集しました'
      redirect_to root_path
    else
      flash.now[:denger]='編集に失敗しました'
      render :edit
    end
  
  end
  
  private
  
  def question_params
    params.require(:question).permit(:year,:number,:sentence,:answer,:text,:category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the Exercises</h1>
    
  </div>
</div>


    <div style="text-align:center;">
        
        <% @categories.each do |category| %>
          <ul style="list-style: none;">
          <li><%=link_to category.name,category_path(category) %></li>
          </ul>
        <% end %>
        
    </div>

<script>
$(function(){
 
 
});
  
  
</script>

app/views/categories/show.html.erb
<h2 class="category-name"><%=@category.name %></h2>

<%=render 'questions/question',questions: @category.questions %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Exercises</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to '問題登録',new_question_path, class: "nav-link" %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Exercises</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="question-list">
    <% questions.each do |question| %>
      <div class="question-item">
        <p><%= question.year %>-<%= question.number %></p>
        <p><%= simple_format(question.sentence) %></p>
        
       
          <p class="btn btn-light btn-block answer-show">答えを見る</p>
          
            <div class="answer">
              <p class="answer-number">(<%= question.answer %>)</p>
              <p class="answer-text"><%= simple_format(question.text) %></p>
            </div>
            
          <%=link_to "編集",edit_question_path(question),class: 'btn btn-light btn-block'%>
        
        <script type="text/javascript">
            $(function () {
              $('.answer').hide();
              
              $('.answer-show').on('click', () => {
                
                $('.answer').show();
               });
               
               
            });
            
            
        </script>

        
      </div>
    <% end %>
</div>

app/views/questions/edit.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @question,local:true) do |f| %>
         <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group">
            <%= f.label :name, '分野' %>
            <%= f.collection_select :category_id, Category.all, :id, :name,{ prompt: "選択してください" } %>
        </div>
        
        <div class="form-group">
            <%= f.label :year, '回' %>
            <%= f.select :year, [["35","35"],["34", "34"], ["33", "33"], ["32", "32"], ["31", "31"]], include_blank: "選択する" %>
        </div>
        
        <div class="form-group">
            <%= f.label :number, '番号' %>
            <%= f.number_field :number, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :sentence, '問題文' %>
            <%= f.text_area :sentence, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :answer, '答え' %>
            <%= f.select :answer, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"],["5","5"]], include_blank: "選択する" %>
        </div>
        
        <div class="form-group">
            <%= f.label :text, '解説' %>
            <%= f.text_area :text, class: 'form-control' %>
        </div>
        
        <%= f.submit'登録する',class: 'btn btn-primary btn-block' %>
        <% end %>
    </div>
</div>

app/views/questions/new.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @question,local:true) do |f| %>
         <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group">
            <%= f.label :name, '分野' %>
            <%= f.collection_select :category_id, Category.all, :id, :name,{ prompt: "選択してください" } %>
        </div>
        
        <div class="form-group">
            <%= f.label :year, '回' %>
            <%= f.select :year, [["35","35"],["34", "34"], ["33", "33"], ["32", "32"], ["31", "31"]], include_blank: "選択する" %>
        </div>
        
        <div class="form-group">
            <%= f.label :number, '番号' %>
            <%= f.number_field :number, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :sentence, '問題文' %>
            <%= f.text_area :sentence, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :answer, '答え' %>
            <%= f.select :answer, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"],["5","5"]], include_blank: "選択する" %>
        </div>
        
        <div class="form-group">
            <%= f.label :text, '解説' %>
            <%= f.text_area :text, class: 'form-control' %>
        </div>
        
        <%= f.submit'登録する',class: 'btn btn-primary btn-block' %>
        <% end %>
    </div>
</div>